name: DeathPunish
main: com.deathPunish.DeathPunish
version: 1.3.8
api-version: 1.13
folia-supported: true
softdepend: [Vault]
commands:
  deathpunish:
    description: 死亡惩罚
    usage: /deathpunish
    aliases:
      - dp
  set:
    #描述这个命令
    description: 设置玩家最大生命值
    #用法
    usage: /deathpunish set <player> <maxhealth> <true/false>
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  add:
    #描述这个命令
    description:
    #用法
    usage: /deathpunish add <player> <amount>
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  get:
    #描述这个命令
    description:
    #用法
    usage: /deathpunish get <player>
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  give:
    #描述这个命令
    description:
    #用法
    usage: /deathpunish give <player> <amount>
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  reload:
    #描述这个命令
    description: 重载插件配置
    #用法
    usage: /deathpunish reload
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！

permissions:
  deathpunish.command:
    description: deathpunish command permission
    default: op
  deathpunish.bypass:
    description: deathpunish bypass permission
    default: false
  deathpunish.craft:
    description: 允许制作回血物品
    default: true
  deathpunish.protect:
    description: 允许使用死亡保护物品
    default: true
